name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore DevOpsLab.slnx

      - name: Build solution
        run: dotnet build DevOpsLab.slnx --no-restore

      - name: Publish application
        run: dotnet publish DevOpsLab.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-lab
          path: ./publish

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-lab:${{ github.sha }} .

      - name: Run Docker container
        run: docker run --rm devops-lab:${{ github.sha }}

      - name: Azure Login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: az acr login --name devopslab

      - name: Tag Docker image for ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker tag devops-lab:${{ github.sha }} devopslab.azurecr.io/devops-lab:${{ github.sha }}

      - name: Push Docker image to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push devopslab.azurecr.io/devops-lab:${{ github.sha }}